Repository CS2103JAN2018-W14-B2/main, pull requests merged in 2018-04, with the labels that each got.

#129 Fix apply shift timetable bug
  src/main/java/seedu/ptman/ui/TimetablePanel.java
Labels: type.bug

#130 Add main command
  docs/UserGuide.adoc
  src/main/java/seedu/ptman/commons/events/ui/EmployeePanelSelectionChangedEvent.java
  src/main/java/seedu/ptman/logic/commands/MainCommand.java
  src/main/java/seedu/ptman/logic/parser/PartTimeManagerParser.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/test/java/seedu/ptman/logic/commands/MainCommandTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
Labels: type.enhancement

#131 Change shifts to use dates instead of days
  src/main/java/seedu/ptman/logic/commands/AddShiftCommand.java
  src/main/java/seedu/ptman/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/ptman/logic/parser/CliSyntax.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/outlet/Date.java
  src/main/java/seedu/ptman/model/outlet/Day.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/model/outlet/Shift.java
  src/main/java/seedu/ptman/model/outlet/Timetable.java
  src/main/java/seedu/ptman/model/outlet/TimetableDay.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/test/java/seedu/ptman/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/ptman/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ptman/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/UnapplyCommandTest.java
  src/test/java/seedu/ptman/logic/parser/AddShiftCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ptman/model/outlet/DateTest.java
  src/test/java/seedu/ptman/model/outlet/DayTest.java
  src/test/java/seedu/ptman/model/outlet/ShiftTest.java
  src/test/java/seedu/ptman/model/outlet/TimetableTest.java
  src/test/java/seedu/ptman/model/outlet/UniqueShiftListTest.java
  src/test/java/seedu/ptman/testutil/ShiftBuilder.java
  src/test/java/seedu/ptman/testutil/ShiftUtil.java
  src/test/java/seedu/ptman/testutil/TypicalShifts.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
  src/test/java/seedu/ptman/ui/testutil/GuiTestAssert.java
Labels: status.ongoing, type.enhancement

#134 Save shifts to local storage
  src/main/java/seedu/ptman/model/outlet/Shift.java
  src/main/java/seedu/ptman/storage/XmlAdaptedShift.java
  src/main/java/seedu/ptman/storage/XmlSerializablePartTimeManager.java
  src/test/java/seedu/ptman/storage/XmlAdaptedShiftTest.java
  src/test/java/seedu/ptman/testutil/ShiftBuilder.java
  src/test/java/seedu/ptman/testutil/TypicalShifts.java
Labels: priority.high, status.ongoing, type.enhancement

#135 Do not include password when checking employee equality
  src/main/java/seedu/ptman/model/employee/Employee.java
Labels: type.bug

#136 Refactor classes and update comments
  .gitignore
  src/main/java/seedu/ptman/commons/util/DateUtil.java
  src/main/java/seedu/ptman/logic/Logic.java
  src/main/java/seedu/ptman/logic/LogicManager.java
  src/main/java/seedu/ptman/logic/commands/AddShiftCommand.java
  src/main/java/seedu/ptman/logic/commands/ApplyCommand.java
  src/main/java/seedu/ptman/logic/commands/DeleteShiftCommand.java
  src/main/java/seedu/ptman/logic/commands/UnapplyCommand.java
  src/main/java/seedu/ptman/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/ReadOnlyPartTimeManager.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/model/outlet/Timetable.java
  src/main/java/seedu/ptman/model/shift/Capacity.java
  src/main/java/seedu/ptman/model/shift/Date.java
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/main/java/seedu/ptman/model/shift/Time.java
  src/main/java/seedu/ptman/model/shift/UniqueShiftList.java
  src/main/java/seedu/ptman/storage/XmlAdaptedShift.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/test/java/seedu/ptman/commons/util/DateUtilTest.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandIntegrationTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/ptman/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ptman/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/LogInAdminCommandTest.java
  src/test/java/seedu/ptman/logic/commands/UnapplyCommandTest.java
  src/test/java/seedu/ptman/logic/parser/AddShiftCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/ApplyCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/DeleteShiftCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/logic/parser/UnapplyCommandParserTest.java
  src/test/java/seedu/ptman/model/PartTimeManagerTest.java
  src/test/java/seedu/ptman/model/outlet/TimetableTest.java
  src/test/java/seedu/ptman/model/shift/CapacityTest.java
  src/test/java/seedu/ptman/model/shift/DateTest.java
  src/test/java/seedu/ptman/model/shift/ShiftTest.java
  src/test/java/seedu/ptman/model/shift/TimeTest.java
  src/test/java/seedu/ptman/model/shift/UniqueShiftListTest.java
  src/test/java/seedu/ptman/storage/XmlAdaptedShiftTest.java
  src/test/java/seedu/ptman/testutil/ShiftBuilder.java
  src/test/java/seedu/ptman/testutil/ShiftUtil.java
  src/test/java/seedu/ptman/testutil/TypicalShifts.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
  src/test/java/seedu/ptman/ui/testutil/GuiTestAssert.java
Labels: type.task

#139 Check if shift is full when adding employees to it
  src/main/java/seedu/ptman/logic/commands/AddShiftCommand.java
  src/main/java/seedu/ptman/logic/commands/ApplyCommand.java
  src/main/java/seedu/ptman/logic/commands/DeleteShiftCommand.java
  src/main/java/seedu/ptman/logic/commands/UnapplyCommand.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/main/java/seedu/ptman/model/shift/UniqueShiftList.java
  src/main/java/seedu/ptman/model/shift/exceptions/DuplicateShiftException.java
  src/main/java/seedu/ptman/model/shift/exceptions/ShiftFullException.java
  src/main/java/seedu/ptman/model/shift/exceptions/ShiftNotFoundException.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/ptman/logic/commands/LogInAdminCommandTest.java
  src/test/java/seedu/ptman/model/shift/ShiftTest.java
  src/test/java/seedu/ptman/model/shift/UniqueShiftListTest.java
  src/test/java/seedu/ptman/testutil/TypicalShifts.java
Labels: type.bug

#142 Update ApplyCommand to not require password in admin mode
  src/main/java/seedu/ptman/logic/commands/ApplyCommand.java
  src/main/java/seedu/ptman/logic/commands/UnapplyCommand.java
  src/main/java/seedu/ptman/logic/commands/UndoableCommand.java
  src/main/java/seedu/ptman/logic/commands/exceptions/MissingPasswordException.java
  src/main/java/seedu/ptman/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ApplyCommandParser.java
  src/main/java/seedu/ptman/logic/parser/DeleteShiftCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/logic/parser/UnapplyCommandParser.java
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/test/java/seedu/ptman/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/ptman/logic/commands/UnapplyCommandTest.java
  src/test/java/seedu/ptman/logic/parser/ApplyCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
Labels: priority.high, type.enhancement

#145 Encrypt shift in storage
  src/main/java/seedu/ptman/storage/XmlAdaptedShift.java
  src/test/java/seedu/ptman/storage/XmlAdaptedShiftTest.java
Labels: priority.low, type.enhancement

#146 update UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/OutletInformationClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/OutletInformationClassDiagram.png
  docs/images/OutletInformationEncryptedXMLFile.jpg
  docs/images/StorageClassDiagram.png
Labels: type.task

#148 Update author annotation
  src/main/java/seedu/ptman/commons/encrypter/DataEncrypter.java
  src/main/java/seedu/ptman/commons/events/model/OutletDataChangedEvent.java
  src/main/java/seedu/ptman/commons/events/ui/AnnouncementChangedEvent.java
  src/main/java/seedu/ptman/commons/events/ui/OutletInformationChangedEvent.java
  src/main/java/seedu/ptman/commons/events/ui/OutletNameChangedEvent.java
  src/main/java/seedu/ptman/logic/commands/AnnouncementCommand.java
  src/main/java/seedu/ptman/logic/commands/EditOutletCommand.java
  src/main/java/seedu/ptman/logic/commands/ViewOutletCommand.java
  src/main/java/seedu/ptman/logic/parser/AnnouncementCommandParser.java
  src/main/java/seedu/ptman/logic/parser/EditOutletCommandParser.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/outlet/Announcement.java
  src/main/java/seedu/ptman/model/outlet/OperatingHours.java
  src/main/java/seedu/ptman/model/outlet/OutletContact.java
  src/main/java/seedu/ptman/model/outlet/OutletEmail.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/model/outlet/OutletName.java
  src/main/java/seedu/ptman/model/outlet/exceptions/NoOutletInformationFieldChangeException.java
  src/main/java/seedu/ptman/storage/OutletInformationStorage.java
  src/main/java/seedu/ptman/storage/StorageManager.java
  src/main/java/seedu/ptman/storage/XmlAdaptedOutletInformation.java
  src/main/java/seedu/ptman/storage/XmlOutletFileStorage.java
  src/main/java/seedu/ptman/storage/XmlOutletInformationStorage.java
  src/main/java/seedu/ptman/ui/OutletDetailsPanel.java
  src/test/java/seedu/ptman/logic/commands/AnnouncementCommandTest.java
  src/test/java/seedu/ptman/logic/commands/EditOutletCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ViewOutletCommandTest.java
  src/test/java/seedu/ptman/logic/parser/AnnouncementCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/EditOutletCommandParserTest.java
  src/test/java/seedu/ptman/model/outlet/NameTest.java
  src/test/java/seedu/ptman/model/outlet/OperatingHoursTest.java
  src/test/java/seedu/ptman/model/outlet/OutletInformationTest.java
  src/test/java/seedu/ptman/storage/XmlAdaptedOutletInformationTest.java
  src/test/java/seedu/ptman/storage/XmlOutletInformationStorageTest.java
Labels: priority.low, type.task

#151 Fix list cell
  src/main/resources/view/PtmanTheme.css
Labels: type.bug

#153 Add author annotation
  src/main/java/seedu/ptman/commons/events/model/UserModeChangedEvent.java
  src/main/java/seedu/ptman/commons/events/ui/ExportTimetableAsImageAndEmailRequestEvent.java
  src/main/java/seedu/ptman/commons/events/ui/ExportTimetableAsImageRequestEvent.java
  src/main/java/seedu/ptman/commons/events/ui/OutletInformationChangedEvent.java
  src/main/java/seedu/ptman/commons/events/ui/OutletNameChangedEvent.java
  src/main/java/seedu/ptman/commons/services/EmailService.java
  src/main/java/seedu/ptman/logic/commands/ExportCommand.java
  src/main/java/seedu/ptman/logic/commands/MainCommand.java
  src/main/java/seedu/ptman/logic/parser/ExportCommandParser.java
  src/main/java/seedu/ptman/ui/AdminModeDisplay.java
  src/main/java/seedu/ptman/ui/OutletDetailsPanel.java
  src/main/java/seedu/ptman/ui/PtmanLogoDisplay.java
  src/main/resources/view/AdminModeDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OutletDetailsPanel.fxml
  src/main/resources/view/PtmanLogoDisplay.fxml
  src/main/resources/view/TimetableView.fxml
  src/test/java/guitests/guihandles/TimetableViewHandle.java
  src/test/java/seedu/ptman/logic/commands/MainCommandTest.java
  src/test/java/seedu/ptman/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/PartTimeManagerSystemTest.java
Labels: type.task

#154 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ShiftIndexBad.png
  docs/images/ShiftIndexGood.png
Labels: type.task

#157 fix password visible by highlighting and funny behavior with the caret
  src/main/java/seedu/ptman/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PtmanTheme.css
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/ptman/ui/CommandBoxTest.java
  src/test/java/systemtests/PartTimeManagerSystemTest.java
Labels: type.bug

#156 Update UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/Ui_add1.png
  docs/images/Ui_add2.png
  docs/images/Ui_announcement1.png
  docs/images/Ui_announcement2.png
  docs/images/Ui_editoutlet1.png
  docs/images/Ui_editoutlet2.png
  docs/images/Ui_help.png
  docs/images/Ui_startup.png
Labels: type.task

#162 Remove an employee from all shifts when he is deleted from PTMan
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/employee/UniqueEmployeeList.java
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/main/java/seedu/ptman/storage/XmlAdaptedShift.java
  src/test/java/seedu/ptman/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/ptman/logic/commands/UnapplyCommandTest.java
  src/test/java/seedu/ptman/storage/XmlAdaptedShiftTest.java
  src/test/java/seedu/ptman/testutil/ShiftBuilder.java
Labels: type.bug

#159 Use figure references in docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.task

#167 Update project portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/shannonwong.adoc
Labels: type.task

#170 fix OperatingHours bug
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/model/outlet/OperatingHours.java
  src/test/java/seedu/ptman/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ptman/model/outlet/OperatingHoursTest.java
Labels: type.bug

#171 Documentation update
  docs/UserGuide.adoc
Labels: type.task

#169 More relevant sample util
  src/main/java/seedu/ptman/model/util/SampleDataUtil.java
  src/main/resources/view/PtmanTheme.css
  src/test/java/seedu/ptman/ui/testutil/GuiTestAssert.java
Labels: type.task

#195 update time input to HHMM format
  src/main/java/seedu/ptman/model/outlet/OperatingHours.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/ui/OutletDetailsPanel.java
  src/test/java/seedu/ptman/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ptman/logic/commands/EditOutletCommandTest.java
  src/test/java/seedu/ptman/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/model/ModelManagerTest.java
  src/test/java/seedu/ptman/model/outlet/OperatingHoursTest.java
  src/test/java/seedu/ptman/model/outlet/OutletInformationTest.java
  src/test/java/seedu/ptman/storage/XmlAdaptedOutletInformationTest.java
  src/test/java/seedu/ptman/storage/XmlOutletInformationStorageTest.java
Labels: type.bug

#192 Add navigation of timetable week
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Feature_Timetable1.png
  docs/images/Feature_Timetable2.png
  docs/images/Feature_Timetable3.png
  src/main/java/seedu/ptman/commons/events/ui/TimetableWeekChangeRequestEvent.java
  src/main/java/seedu/ptman/commons/util/DateUtil.java
  src/main/java/seedu/ptman/logic/Logic.java
  src/main/java/seedu/ptman/logic/LogicManager.java
  src/main/java/seedu/ptman/logic/commands/ExportCommand.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/shift/exceptions/DuplicateShiftException.java
  src/main/java/seedu/ptman/ui/MainWindow.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PtmanTheme.css
  src/main/resources/view/TimetablePanel.fxml
  src/main/resources/view/TimetableView.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/TimetablePanelHandle.java
  src/test/java/guitests/guihandles/TimetableViewHandle.java
  src/test/java/seedu/ptman/commons/util/DateUtilTest.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/LogInAdminCommandTest.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
  src/test/java/systemtests/PartTimeManagerSystemTest.java
Labels: priority.high, status.ongoing, type.enhancement

#198 Add salary command
  collated/functional/SunBangjie.md
  collated/functional/hzxcaryn.md
  collated/functional/koo1993.md
  collated/functional/shanwpf.md
  collated/test/SunBangjie.md
  collated/test/hzxcaryn.md
  collated/test/koo1993.md
  collated/test/shanwpf.md
  src/main/java/seedu/ptman/logic/commands/AddSalaryCommand.java
  src/main/java/seedu/ptman/logic/commands/ResetAdminPasswordCommand.java
  src/main/java/seedu/ptman/logic/commands/ResetPasswordCommand.java
  src/main/java/seedu/ptman/logic/parser/AddSalaryCommandParser.java
  src/main/java/seedu/ptman/logic/parser/PartTimeManagerParser.java
  src/test/java/seedu/ptman/logic/commands/AddSalaryCommandTest.java
  src/test/java/seedu/ptman/logic/parser/AddSalaryCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: type.task

#201 Polish the Shifts feature
  src/main/java/seedu/ptman/logic/commands/AddShiftCommand.java
  src/main/java/seedu/ptman/logic/commands/ApplyCommand.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/model/shift/Date.java
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandIntegrationTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ptman/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ptman/model/shift/DateTest.java
  src/test/java/seedu/ptman/testutil/ShiftBuilder.java
Labels: priority.medium, type.enhancement

#208 Fix backup files
  src/main/java/seedu/ptman/MainApp.java
  src/main/java/seedu/ptman/storage/OutletInformationStorage.java
  src/main/java/seedu/ptman/storage/StorageManager.java
  src/main/java/seedu/ptman/storage/XmlOutletInformationStorage.java
  src/test/data/XmlOutletInformationStorageTest/backupFile.backup
  src/test/data/XmlPartTimeManagerStorageTest/backupFile.backup
  src/test/java/seedu/ptman/commons/encrypter/EncrypterTest.java
  src/test/java/seedu/ptman/storage/StorageManagerTest.java
  src/test/java/seedu/ptman/storage/XmlOutletInformationStorageTest.java
  src/test/java/seedu/ptman/storage/XmlPartTimeManagerStorageTest.java
Labels: type.enhancement

#204 Display an error message when a shift's start time is after end time
  src/main/java/seedu/ptman/logic/commands/AddShiftCommand.java
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandIntegrationTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ViewShiftCommandTest.java
  src/test/java/seedu/ptman/model/PartTimeManagerTest.java
  src/test/java/seedu/ptman/model/shift/ShiftTest.java
  src/test/java/seedu/ptman/model/shift/UniqueShiftListTest.java
  src/test/java/seedu/ptman/storage/XmlAdaptedShiftTest.java
  src/test/java/seedu/ptman/storage/XmlEncryptedAdaptedShiftTest.java
  src/test/java/seedu/ptman/testutil/ShiftBuilder.java
  src/test/java/seedu/ptman/testutil/TypicalShifts.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
Labels: priority.medium, type.enhancement

#212 Update UGDG and Project Portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/EditOutletCommandSequenceDiagram.pptx
  docs/diagrams/IntroductionToOutlet.pptx
  docs/images/DefaultOutlet.jpg
  docs/images/EditOutletCommandSequenceDiagram.png
  docs/images/IntroductionToOutlet.jpg
  docs/images/OutletInformationDecryptedXMLFile.jpg
  docs/images/OutletInformationEncryptedXMLFile.jpg
  docs/images/SuccessfulDecryptCommand.jpg
  docs/images/SuccessfulEncryptCommand.jpg
  docs/images/Ui_announcement2.png
  docs/images/Ui_editoutlet2.png
  docs/images/Ui_editoutlet3.png
  docs/images/announcementdisplay.jpg
  docs/images/outletinformationdisplay.jpg
  docs/team/SunBangJie.adoc
Labels: type.task

#214 Do not allow users to apply for shifts that are over
  src/main/java/seedu/ptman/logic/commands/ApplyCommand.java
  src/main/java/seedu/ptman/model/shift/Date.java
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/main/java/seedu/ptman/model/shift/Time.java
  src/test/java/seedu/ptman/logic/commands/ApplyCommandTest.java
Labels: priority.medium, type.enhancement

#215 Update documentation
  docs/UserGuide.adoc
  docs/team/shannonwong.adoc
Labels: type.task

#217 Remove browser panel
  src/main/java/seedu/ptman/ui/BrowserPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/ptman/ui/BrowserPanelTest.java
  src/test/java/systemtests/PartTimeManagerSystemTest.java
Labels: type.task

#216 Update docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/updateTimetableViewSequenceDiagram.pptx
  docs/diagrams/updateTimetableViewSequenceDiagrams.pptx
  docs/images/TimetablePanelClassDiagram.png
  docs/images/Ui.png
  docs/images/updateTimetableViewHighLevelSequenceDiagram.png
  docs/images/updateTimetableViewSequenceDiagram.png
  docs/team/SunBangJie.adoc
  docs/team/hzxcaryn.adoc
  docs/team/koo1993.adoc
  docs/team/shannonwong.adoc
  src/main/java/seedu/ptman/ui/TimetablePanel.java
Labels: type.task

#226 fix left right bug for timetable
  docs/UserGuide.adoc
  src/main/java/seedu/ptman/commons/events/ui/TimetableWeekChangeRequestEvent.java
  src/main/java/seedu/ptman/ui/MainWindow.java
Labels: type.bug

#227 Add more employees and shifts into sample util
  docs/team/hzxcaryn.adoc
  src/main/java/seedu/ptman/model/shift/Shift.java
  src/main/java/seedu/ptman/model/util/SampleDataUtil.java
  src/test/data/XmlSerializablePartTimeManagerTest/typicalEncryptedEmployeesPartTimeManager.xml
  src/test/java/seedu/ptman/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/SampleDataTest.java
Labels: type.task

#236 Update PPP & UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/hzxcaryn.adoc
  docs/team/koo1993.adoc
  docs/team/shanwpf.adoc
Labels: type.task

#240 Solve timetable rescaling bug
  docs/DeveloperGuide.adoc
  docs/team/hzxcaryn.adoc
  src/main/java/seedu/ptman/ui/TimetablePanel.java
Labels: type.bug

#243 Update DG and AboutUs
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/ptman/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/ptman/commons/util/AppUtilTest.java
Labels: type.task
