Repository CS2103JAN2018-W14-B2/main, pull requests merged in 2018-03, with the labels that each got.

#13 Update user guide
  docs/UserGuide.adoc
Labels: type.task

#11 Update developer guide
  docs/DeveloperGuide.adoc
Labels: type.task

#17 Update developer guide formatting (Dev Ops and User Stories)
  docs/DeveloperGuide.adoc
Labels: type.task

#23 Update formatting of Developer Guide (Documentation and Testing)
  docs/DeveloperGuide.adoc
Labels: type.task

#28 Update README
  README.adoc
Labels: type.task

#29 Update AboutUs and add portfolio
  docs/AboutUs.adoc
  docs/images/damithc.jpg
  docs/images/shanwpf.jpg
  docs/team/shannonwong.adoc
Labels: type.task

#27 Create OutletInformation class to store some basic information
  src/main/java/seedu/ptman/model/outlet/Name.java
  src/main/java/seedu/ptman/model/outlet/OperatingHours.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/test/java/seedu/ptman/model/outlet/NameTest.java
  src/test/java/seedu/ptman/model/outlet/OperatingHoursTest.java
  src/test/java/seedu/ptman/model/outlet/OutletInformationTest.java
Labels: status.ongoing, type.task

#35 Update UI Mockup
  docs/images/Ui.png
Labels: type.task

#14 Update developer guide on formatting and grammar
  docs/DeveloperGuide.adoc
Labels: type.task

#58 Access control done!
  src/main/java/seedu/ptman/logic/LogicManager.java
  src/main/java/seedu/ptman/logic/commands/AddCommand.java
  src/main/java/seedu/ptman/logic/commands/ClearCommand.java
  src/main/java/seedu/ptman/logic/commands/Command.java
  src/main/java/seedu/ptman/logic/commands/DeleteCommand.java
  src/main/java/seedu/ptman/logic/commands/EditCommand.java
  src/main/java/seedu/ptman/logic/commands/RedoCommand.java
  src/main/java/seedu/ptman/logic/commands/UndoCommand.java
  src/main/java/seedu/ptman/logic/parser/AddCommandParser.java
  src/main/java/seedu/ptman/logic/parser/CliSyntax.java
  src/main/java/seedu/ptman/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/ptman/logic/parser/EditCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/logic/parser/PartTimeManagerParser.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/Password.java
  src/main/java/seedu/ptman/model/employee/Employee.java
  src/main/java/seedu/ptman/model/employee/exceptions/InvalidPasswordException.java
  src/main/java/seedu/ptman/model/util/SampleDataUtil.java
  src/main/java/seedu/ptman/storage/XmlAdaptedEmployee.java
  src/test/data/XmlPartTimeManagerStorageTest/invalidAndValidEmployeePartTimeManager.xml
  src/test/data/XmlSerializablePartTimeManagerTest/typicalEmployeesPartTimeManager.xml
  src/test/data/XmlUtilTest/invalidEmployeeField.xml
  src/test/data/XmlUtilTest/validEmployee.xml
  src/test/data/XmlUtilTest/validPartTimeManager.xml
  src/test/java/seedu/ptman/commons/util/XmlUtilTest.java
  src/test/java/seedu/ptman/logic/LogicManagerTest.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ptman/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/ptman/model/PasswordTest.java
  src/test/java/seedu/ptman/storage/XmlAdaptedEmployeeTest.java
  src/test/java/seedu/ptman/testutil/EmployeeBuilder.java
  src/test/java/seedu/ptman/testutil/EmployeeUtil.java
  src/test/java/seedu/ptman/testutil/TypicalEmployees.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/PartTimeManagerSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high

#64 Create and implement delete shift command
  src/main/java/seedu/ptman/commons/core/Messages.java
  src/main/java/seedu/ptman/logic/commands/DeleteShiftCommand.java
  src/main/java/seedu/ptman/logic/parser/DeleteShiftCommandParser.java
  src/main/java/seedu/ptman/logic/parser/PartTimeManagerParser.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/outlet/Day.java
  src/main/java/seedu/ptman/model/outlet/Shift.java
  src/main/java/seedu/ptman/model/outlet/Time.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/ptman/logic/parser/DeleteShiftCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/testutil/ShiftUtil.java
  src/test/java/seedu/ptman/testutil/TypicalIndexes.java
Labels: priority.high, type.enhancement

#71 Add Contact to OutletInformation
  docs/DeveloperGuide.adoc
  src/main/java/seedu/ptman/logic/commands/EditOutletCommand.java
  src/main/java/seedu/ptman/logic/parser/CliSyntax.java
  src/main/java/seedu/ptman/logic/parser/EditOutletCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/outlet/OutletContact.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/model/outlet/exceptions/NoOutletInformationFieldChangeException.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ptman/logic/commands/EditOutletCommandTest.java
  src/test/java/seedu/ptman/logic/commands/LogInAdminCommandTest.java
  src/test/java/seedu/ptman/logic/parser/EditOutletCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/model/outlet/OutletInformationTest.java
Labels: priority.medium, type.task

#73 Update undo editoutlet command
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/ReadOnlyPartTimeManager.java
  src/test/java/seedu/ptman/model/PartTimeManagerTest.java
Labels: priority.low, type.task

#54 UI modifications (Outlet Panel and Timetable GUI)
  build.gradle
  libs/README-EXT.txt
  libs/calendarfx-recurrence-8.4.0.jar
  libs/calendarfx-view-8.4.0.jar
  libs/controlsfx-8.40.11.jar
  libs/fontawesomefx-commons-8.13.jar
  libs/fontawesomefx-fontawesome-4.7.0-1.jar
  libs/license4j-1.4.0.jar
  src/main/java/seedu/ptman/commons/core/Config.java
  src/main/java/seedu/ptman/commons/events/ui/OutletInformationChangedEvent.java
  src/main/java/seedu/ptman/commons/events/ui/OutletNameChangedEvent.java
  src/main/java/seedu/ptman/logic/Logic.java
  src/main/java/seedu/ptman/logic/LogicManager.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/ReadOnlyPartTimeManager.java
  src/main/java/seedu/ptman/model/outlet/Capacity.java
  src/main/java/seedu/ptman/model/outlet/Shift.java
  src/main/java/seedu/ptman/ui/EmployeeListPanel.java
  src/main/java/seedu/ptman/ui/MainWindow.java
  src/main/java/seedu/ptman/ui/OutletDetailsPanel.java
  src/main/java/seedu/ptman/ui/ResultDisplay.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/main/java/seedu/ptman/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EmployeeListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OutletDetailsPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TimetableView.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/OutletDetailsPanelHandle.java
  src/test/java/guitests/guihandles/TimetableViewHandle.java
  src/test/java/seedu/ptman/commons/core/ConfigTest.java
  src/test/java/seedu/ptman/ui/OutletDetailsPanelTest.java
  src/test/java/seedu/ptman/ui/ResultDisplayTest.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/PartTimeManagerSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, type.enhancement

#83 Add email in outlet information
  src/main/java/seedu/ptman/logic/commands/EditOutletCommand.java
  src/main/java/seedu/ptman/logic/parser/CliSyntax.java
  src/main/java/seedu/ptman/logic/parser/EditOutletCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/ReadOnlyPartTimeManager.java
  src/main/java/seedu/ptman/model/outlet/OutletEmail.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ptman/logic/commands/EditOutletCommandTest.java
  src/test/java/seedu/ptman/logic/commands/LogInAdminCommandTest.java
  src/test/java/seedu/ptman/logic/parser/EditOutletCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/model/PartTimeManagerTest.java
  src/test/java/seedu/ptman/model/outlet/OutletInformationTest.java
Labels: priority.low, type.enhancement

#93 Fix redo for outlet and shift commnads
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/Password.java
  src/main/java/seedu/ptman/model/ReadOnlyPartTimeManager.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/model/outlet/Timetable.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/LogInAdminCommandTest.java
  src/test/java/seedu/ptman/model/ModelManagerTest.java
  src/test/java/seedu/ptman/model/PartTimeManagerTest.java
  src/test/java/seedu/ptman/model/PasswordTest.java
  src/test/java/seedu/ptman/model/outlet/TimetableTest.java
Labels: type.bug

#96 Store outlet info
  dummy
  src/main/java/seedu/ptman/MainApp.java
  src/main/java/seedu/ptman/commons/events/model/OutletDataChangedEvent.java
  src/main/java/seedu/ptman/commons/events/ui/AnnouncementChangedEvent.java
  src/main/java/seedu/ptman/logic/commands/AnnouncementCommand.java
  src/main/java/seedu/ptman/logic/commands/UndoableCommand.java
  src/main/java/seedu/ptman/logic/commands/ViewOutletCommand.java
  src/main/java/seedu/ptman/logic/parser/AnnouncementCommandParser.java
  src/main/java/seedu/ptman/logic/parser/PartTimeManagerParser.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/UserPrefs.java
  src/main/java/seedu/ptman/model/outlet/Announcement.java
  src/main/java/seedu/ptman/model/outlet/OperatingHours.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/storage/OutletInformationStorage.java
  src/main/java/seedu/ptman/storage/Storage.java
  src/main/java/seedu/ptman/storage/StorageManager.java
  src/main/java/seedu/ptman/storage/XmlAdaptedOutletInformation.java
  src/main/java/seedu/ptman/storage/XmlOutletFileStorage.java
  src/main/java/seedu/ptman/storage/XmlOutletInformationStorage.java
  src/main/java/seedu/ptman/ui/OutletDetailsPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/OutletDetailsPanel.fxml
  src/test/data/XmlOutletInformationStorageTest/NotXmlFormatOutletInformation.xml
  src/test/data/XmlOutletInformationStorageTest/invalidOutletInformation.xml
  src/test/java/guitests/guihandles/OutletDetailsPanelHandle.java
  src/test/java/seedu/ptman/TestApp.java
  src/test/java/seedu/ptman/logic/LogicManagerTest.java
  src/test/java/seedu/ptman/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandIntegrationTest.java
  src/test/java/seedu/ptman/logic/commands/AnnouncementCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ClearCommandTest.java
  src/test/java/seedu/ptman/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/ptman/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/EditCommandTest.java
  src/test/java/seedu/ptman/logic/commands/EditOutletCommandTest.java
  src/test/java/seedu/ptman/logic/commands/FindCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ListCommandTest.java
  src/test/java/seedu/ptman/logic/commands/RedoCommandTest.java
  src/test/java/seedu/ptman/logic/commands/SelectCommandTest.java
  src/test/java/seedu/ptman/logic/commands/UndoCommandTest.java
  src/test/java/seedu/ptman/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ViewOutletCommandTest.java
  src/test/java/seedu/ptman/logic/parser/AnnouncementCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/model/ModelManagerTest.java
  src/test/java/seedu/ptman/model/outlet/OutletInformationTest.java
  src/test/java/seedu/ptman/storage/StorageManagerTest.java
  src/test/java/seedu/ptman/storage/XmlAdaptedOutletInformationTest.java
  src/test/java/seedu/ptman/storage/XmlOutletInformationStorageTest.java
  src/test/java/seedu/ptman/ui/OutletDetailsPanelTest.java
Labels: priority.high, type.enhancement

#99 update UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.low

#98 UI updates
  docs/DeveloperGuide.adoc
  src/main/java/seedu/ptman/commons/events/ui/OutletInformationChangedEvent.java
  src/main/java/seedu/ptman/logic/commands/EditOutletCommand.java
  src/main/java/seedu/ptman/logic/commands/UndoableCommand.java
  src/main/java/seedu/ptman/model/outlet/OutletInformation.java
  src/main/java/seedu/ptman/ui/CommandBox.java
  src/main/java/seedu/ptman/ui/MainWindow.java
  src/main/java/seedu/ptman/ui/OutletDetailsPanel.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OutletDetailsPanel.fxml
  src/test/java/guitests/guihandles/OutletDetailsPanelHandle.java
  src/test/java/seedu/ptman/model/outlet/OutletInformationTest.java
  src/test/java/seedu/ptman/ui/OutletDetailsPanelTest.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
  src/test/java/systemtests/PartTimeManagerSystemTest.java
Labels: priority.high, type.enhancement

#100 Update UG for select and export commands
  docs/UserGuide.adoc
Labels: type.task

#103 Fix timetable view bug
  src/main/java/seedu/ptman/ui/TimetablePanel.java
Labels: type.bug

#95 Create and implement apply command
  src/main/java/seedu/ptman/commons/core/index/Index.java
  src/main/java/seedu/ptman/logic/commands/AddShiftCommand.java
  src/main/java/seedu/ptman/logic/commands/ApplyCommand.java
  src/main/java/seedu/ptman/logic/commands/DeleteShiftCommand.java
  src/main/java/seedu/ptman/logic/commands/UndoableCommand.java
  src/main/java/seedu/ptman/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ApplyCommandParser.java
  src/main/java/seedu/ptman/logic/parser/DeleteShiftCommandParser.java
  src/main/java/seedu/ptman/logic/parser/ParserUtil.java
  src/main/java/seedu/ptman/logic/parser/PartTimeManagerParser.java
  src/main/java/seedu/ptman/model/Model.java
  src/main/java/seedu/ptman/model/ModelManager.java
  src/main/java/seedu/ptman/model/PartTimeManager.java
  src/main/java/seedu/ptman/model/employee/Employee.java
  src/main/java/seedu/ptman/model/outlet/Shift.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/test/java/seedu/ptman/logic/commands/AddCommandTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandIntegrationTest.java
  src/test/java/seedu/ptman/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/ApplyCommandTest.java
  src/test/java/seedu/ptman/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/ptman/logic/commands/LogInAdminCommandTest.java
  src/test/java/seedu/ptman/logic/parser/ApplyCommandParserTest.java
  src/test/java/seedu/ptman/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ptman/logic/parser/PartTimeManagerParserTest.java
  src/test/java/seedu/ptman/model/outlet/ShiftTest.java
  src/test/java/seedu/ptman/storage/XmlPartTimeManagerStorageTest.java
  src/test/java/seedu/ptman/testutil/TypicalEmployees.java
  src/test/java/seedu/ptman/testutil/TypicalShifts.java
Labels: priority.high, status.ongoing, type.enhancement

#112 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram - Copy.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/ShiftComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/ShiftClassDiagram.png
Labels: type.task

#127 Export Command to support emailing of exported image
  src/main/java/seedu/ptman/commons/services/EmailService.java
  src/main/java/seedu/ptman/logic/commands/ExportCommand.java
  src/main/java/seedu/ptman/ui/TimetablePanel.java
  src/test/java/seedu/ptman/ui/TimetablePanelTest.java
Labels: type.enhancement
